# Generated by Django 4.2.4 on 2023-08-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_order_payments_order_products_order_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payments',
        ),
    ]
