# Generated by Django 4.2.4 on 2023-08-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_order_payments_order_products_order_total_and_more'),
        ('shipments', '0002_shipment_date_shipment_order_shipment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ManyToManyField(to='orders.order'),
        ),
    ]
