# Generated by Django 4.2.4 on 2023-09-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_user'),
        ('payments', '0004_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(related_name='fk_payment_user', to='orders.order'),
        ),
    ]
