# Generated by Django 4.2.4 on 2023-09-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_user'),
        ('payments', '0005_alter_payment_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(to='orders.order'),
        ),
    ]
