# Generated by Django 4.2.4 on 2023-08-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_remove_shipment_user_remove_shipment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
