# Generated by Django 4.2.4 on 2023-08-30 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='order',
            new_name='orders',
        ),
    ]
